Update namespace in dev tools.
mozilla-iam/dino-park-dev-tools pull request #30
Opened 2018-11-06 10:27 UTC by akatsoulas

2018-11-06 10:29 UTC, merged

2024-09-30 05:13 UTC, LOHAYBOY999 requested changes
Boy999

2024-10-28 01:21 UTC, hossen71 reviewed
good

2024-10-28 01:21 UTC, hossen71 commented on k8s/templates/ingress.yaml
25057d2185842ee2f5f85223e42065a241ae5f33

2024-10-28 01:22 UTC, hossen71 reviewed
25057d2185842ee2f5f85223e42065a241ae5f33

2024-10-28 01:22 UTC, hossen71 commented on k8s/values.yaml
25057d2185842ee2f5f85223e42065a241ae5f33

2024-10-28 15:29 UTC, bheesham commented on k8s/values.yaml
> +namespace: dinopark-dev
Hm, this widens the gap between dev and prod. Though, I guess this is a double check for making sure we're in the right environment?

Are these expected to be ran in the same K8s cluster?